# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2015. #zanata, 2021.
# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2017. #zanata, 2021.
# Casey Jones <nahareport@yahoo.com>, 2020.
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-08-31 01:42+0000\n"
"PO-Revision-Date: 2021-03-31 03:01+0000\n"
"Last-Translator: Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>\n"
"Language-Team: Japanese <https://translate.fedoraproject.org/projects/dnf/"
"dnf-plugins-extras/ja/>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 4.5.2\n"

#: plugins/kickstart.py:57
msgid "Install packages defined in a kickstart file on your system"
msgstr "システム上のキックスタートファイルに定義されたパッケージをインストール"

#: plugins/kickstart.py:62
msgid "kickstart file"
msgstr "キックスタートファイル"

#: plugins/kickstart.py:80
#, python-format
msgid "file cannot be parsed: %s"
msgstr "ファイルがパースできません: %s"

#: plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "rpmconfのハンドリングパッケージリストに '{}' を追加中"

#: plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "rpmconf プラグインは非対話モードで実行されません"

#: plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "MERGE 変数が見つからないため、rpmconfのsys.exitを無視しています"

#: plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "ファイルが見つからないため、rpmconfのsys.exitを無視しています"

#: plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr "アクティブなdnf変数をすべて表示"

#: plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "snapperdに接続できませんでした: %s"

#: plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr "pre_snapshotを作成中"

#: plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr "pre_snapshot %d が作成されました"

#: plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr "pre_snapshot 作成に失敗しました: %s"

#: plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr "pre_snapshot作成に失敗したため、post_snapshotをスキップ中"

#: plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr "post_snapshotを作成中"

#: plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr "post_snapshot %d が作成されました"

#: plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr "post_snapshot 作成に失敗しました: %s"

#. Translators: This string is only used in unit tests.
#: plugins/system_upgrade.py:45
msgid "the color of the sky"
msgstr "空の色"

#: plugins/system_upgrade.py:57
msgid "Need a --releasever greater than the current system version."
msgstr ""
"--releasever は、現在のシステムのバージョン番号よりも大きくなければなりませ"
"ん。"

#. Translators: do not change "reboot" here
#: plugins/system_upgrade.py:59
#, python-brace-format
msgid ""
"Download complete! Use 'dnf {command} reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf {command} clean'"
msgstr ""
"ダウンロード完了! アップグレード開始には 'dnf {command} reboot' を使ってくだ"
"さい。\n"
"キャッシュされた metadata と transaction の削除には 'dnf {command} clean' を"
"使ってください"

#: plugins/system_upgrade.py:62
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""
"すみませんが '--network' の代わりに 'download --releasever' を使う必要があり"
"ます"

#: plugins/system_upgrade.py:71
msgid "Reboot turned off, not rebooting."
msgstr ""

#: plugins/system_upgrade.py:120
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr "スクリーンブランキングは無効にできません: %s"

#: plugins/system_upgrade.py:140
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr "状態ファイル: %s のロードに失敗しました。状態空で続行します。"

#: plugins/system_upgrade.py:286
msgid "The following boots appear to contain upgrade logs:"
msgstr "以下ブートはアップグレードログを含んでいます:"

#: plugins/system_upgrade.py:296
msgid "-- no logs were found --"
msgstr "-- ログが見つかりません --"

#: plugins/system_upgrade.py:311
msgid "Cannot find logs with this index."
msgstr "このインデックスでログが見つかりません。"

#: plugins/system_upgrade.py:320
msgid "Unable to match systemd journal entry"
msgstr "systemdジャーナルエントリーにマッチできません"

#: plugins/system_upgrade.py:341
msgid "Prepare system for upgrade to a new release"
msgstr "システムに新リリースにアップグレードするための準備をしてください"

#: plugins/system_upgrade.py:357
msgid "keep installed packages if the new release's version is older"
msgstr ""
"新しいリリースバージョンがインストール済パッケージより古い場合は維持する"

#: plugins/system_upgrade.py:361
msgid "which logs to show"
msgstr "どのログを表示"

#: plugins/system_upgrade.py:395
#, python-brace-format
msgid "Incompatible version of data. Rerun 'dnf {command} download [OPTIONS]'"
msgstr ""
"データの非互換バージョン。 'dnf {command} download [OPTIONS]' を再実行してく"
"ださい"

#: plugins/system_upgrade.py:432
msgid "Command 'offline-distrosync' cannot be used with --no-downgrade option"
msgstr ""
"コマンド 'offline-distrosync' は --no-downgrade オプションと使用できません"

#: plugins/system_upgrade.py:454
msgid "Additional information for System Upgrade: {}"
msgstr "システムアップグレードの追加情報: {}"

#: plugins/system_upgrade.py:457
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"継続する前に \"dnf --refresh upgrade\" 実行によりシステム全体がアップグレード"
"されることを確認してください。継続しますか"

#: plugins/system_upgrade.py:461
msgid "Operation aborted."
msgstr "操作が中断されました。"

#: plugins/system_upgrade.py:519
msgid "system is not ready for upgrade"
msgstr "システムはアップグレードの準備ができてません。"

#: plugins/system_upgrade.py:522
#, python-brace-format
msgid ""
"the transaction was not prepared for '{command}'. Rerun 'dnf {command} "
"download [OPTIONS]'"
msgstr ""
"トランザクションは '{command}' の準備ができていません。 'dnf {command} "
"download [OPTIONS]' を再実行してください"

#: plugins/system_upgrade.py:526
msgid "upgrade is already scheduled"
msgstr "アップグレードは既に予定されています"

#: plugins/system_upgrade.py:532
msgid "trigger file does not exist. exiting quietly."
msgstr "トリガーファイルが存在しません。終了しています。"

#: plugins/system_upgrade.py:535
msgid "another upgrade tool is running. exiting quietly."
msgstr "他のアップグレードツールが実行されています。終了しています。"

#: plugins/system_upgrade.py:544
#, python-brace-format
msgid "use 'dnf {command} reboot' to begin the upgrade"
msgstr "アップグレード開始には 'dnf {command} reboot' を使用してください"

#: plugins/system_upgrade.py:562
msgid "Rebooting to perform upgrade."
msgstr "アップグレード実行のため再起動中。"

#: plugins/system_upgrade.py:595
msgid "Starting offline upgrade. This will take a while."
msgstr "offline upgradeを起動中。しばらく時間がかかります。"

#: plugins/system_upgrade.py:597
msgid "Starting offline distrosync. This will take a while."
msgstr "offline distrosyncを起動中。しばらく時間がかかります。"

#: plugins/system_upgrade.py:599
msgid "Starting system upgrade. This will take a while."
msgstr "system upgrade を起動中。しばらく時間がかかります。"

#: plugins/system_upgrade.py:615
msgid "Cleaning up downloaded data..."
msgstr "ダウンロード済みデータを掃除しています..."

#: plugins/system_upgrade.py:644
msgid ""
"The system-upgrade transaction is empty, your system is already up-to-date."
msgstr ""

#: plugins/system_upgrade.py:653
msgid "Transaction saved to {}."
msgstr ""

#: plugins/system_upgrade.py:656
msgid "Error storing transaction: {}"
msgstr ""

#: plugins/system_upgrade.py:678
msgid "Download finished."
msgstr "ダウンロード完了。"

#: plugins/system_upgrade.py:681 plugins/system_upgrade.py:682
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "アップグレードは完了しました！ 掃除と再起動中..."

#: plugins/system_upgrade.py:691
msgid "Prepare offline upgrade of the system"
msgstr "システムのoffline upgradeを準備"

#: plugins/system_upgrade.py:696
msgid "Prepare offline distrosync of the system"
msgstr "システムのoffline distrosyncを準備"

#: plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "torproxyプラグインを無効中: Torネットワークに接続できません"

#: plugins/tracer.py:69
msgid "For more information run:"
msgstr "詳細情のため実行:"

#: plugins/tracer.py:96
msgid "Call to Tracer API ended unexpectedly:"
msgstr "Tracer API 呼び出しが予期せず終了しました:"

#: plugins/tracer.py:98
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"https://github.com/FrostyX/tracer/issues に行きこの問題を報告してください。あ"
"りがとうございます"

#: plugins/tracer.py:100
msgid "We apologize for any inconvenience"
msgstr "ご不便をお掛けして申し訳ございません"

#~ msgid "Unable to match package: %s"
#~ msgstr "マッチできませんパッケージ: %s"

#~ msgid "Unable to match some of packages"
#~ msgstr "いくつかのパッケージがマッチできません"
